[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_bolierplate = "J4UfqL2dj6N5mTDxH6yym9ykU1dyP5wW519Ta9obTP9m"
[programs.devnet]
anchor_bolierplate = "J4UfqL2dj6N5mTDxH6yym9ykU1dyP5wW519Ta9obTP9m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/sara.brodin/.config/solana/id.json"

[scripts2]
test = "yarn run mocha -t 1000000 tests/"

[scripts]
test = "node tests/anchorbolierplate.js"
